### ISSUE TITLE
How to debug server side errors?

### ISSUE THREAD

**Issue by kuatro** [janoist1/universal-react-redux-starter-kit#12]
I have a particular page, that works OK when it rendered by the client. But when I trying to render it server-side, it only returns a blank page with `Not Found` caption. In the console or terminal there is no exceptions or errors.

**Comment by janoist1** [comment]
This is a good point. I've tried few things but no luck so far. It's difficult to debug it with all the babel stuff source mapping configured in the IDE (I use WebStorm). These days I'm very busy so that I had no time moving forward with this project, but I'll let you know if any progress happens. Or feel free to contribute. 👍

**Comment by TriPSs** [comment]
Had the same thing, adding an try catch to the renderToString part showed me the error

![image](https://cloud.githubusercontent.com/assets/7668692/18272923/ed234888-743a-11e6-8ab0-e2c7403dfc72.png)

**Comment by janoist1** [comment]
Thats a good and simple solution - I like it - but I was thinking of something like setting up a proper debugging tool that allows us to use breakpoints in the IDE, inspect variables, etc.
I'll adopt @TriPSs idea for now because it's way better than nothing. 👍

**Comment by janoist1** [comment]
I'm gonna close this issue for now.
